language: php
sudo: false
cache:
    directories:
        - $HOME/.composer/cache/files
        - $HOME/symfony-bridge/.phpunit
env:
    global:
        - PHPUNIT_FLAGS="-v"
        - SYMFONY_PHPUNIT_DIR="$HOME/symfony-bridge/.phpunit"
matrix:
    fast_finish: true
    include:
          # Minimum supported dependencies with the latest and oldest PHP version
        - php: 7.4
          env: COMPOSER_FLAGS="--prefer-stable --prefer-lowest" SYMFONY_DEPRECATIONS_HELPER="weak_vendors"
        - php: 7.3
          env: COMPOSER_FLAGS="--prefer-stable --prefer-lowest" SYMFONY_DEPRECATIONS_HELPER="weak_vendors"
          # Test the latest stable release
        - php: 7.3
        - php: 7.4
          env: COVERAGE=true PHPUNIT_FLAGS="-v --coverage-text"
          # Test LTS versions. This makes sure we do not use Symfony packages with version greater
          # than 2 or 3 respectively. Read more at https://github.com/symfony/lts
        - php: 7.4
          env: DEPENDENCIES="symfony/lts:^2"
        - php: 7.4
          env: DEPENDENCIES="symfony/lts:^3"
          # Latest commit to master
        - php: 7.4

install:
  - composer update ${COMPOSER_FLAGS} --no-progress --no-suggest --ansi

script:
  - vendor/bin/simple-phpunit
